# Copyright 2026 NeuroLocate contributors
# SPDX-License-Identifier: Apache-2.0
r"""The training forward models, and the gain bank they produce.

Training a global proposal network needs hundreds of thousands of forward
solutions at *continuous* source positions. Doing that naively is one OpenMEEG
assembly per training sample forever. Two facts make it a one-off cost instead.

**The expensive half does not depend on the source.** The symmetric BEM gives

.. math::  G = R \, S(e) \, A(\sigma)^{-1} \, D(p)

and only ``D`` depends on the dipole. So the source term is assembled **once**
per position and every head model in the training distribution is then a matrix
product against it. The factorization is exact — it is a regrouping of the
symmetric BEM's own linear algebra, not an approximation — and here it is what
gives one set of sources many head models for the price of one assembly.

**The map is linear in the moment.** A position's gain is ``[C, 3]``. Every
orientation, amplitude and time course a training sample could want is a
contraction against it, done on the fly in the data loader. So the bank stores
gains, not EEG, and one bank serves an unbounded number of training samples.

What the bank is *not*
----------------------
It is not an interpolant and it is not a grid. Every stored column is a real
``DipSourceMat`` assembly at a real continuous position — the same call the
optimizer makes at inference. The positions are drawn from the cortical surface
with a normal-direction jitter, so they lie **off** every source space in this
project, including the ico5 space the benchmark's truths are drawn between. A
network trained on this bank cannot learn to snap to a candidate, because there
are no candidates.

The training distribution is not the test distribution
------------------------------------------------------
Every variant here is an OpenMEEG symmetric BEM on ico3 fsaverage — the model the
estimator inverts with. The benchmark's observations are generated by MNE-Python's
linear-collocation BEM on ico4 (:mod:`neurolayout.mismatch`), which none of these
variants is. Training on the inference model is exactly what the gradient-only
estimator does when it inverts with it; the mismatch to the generator is what
keeps the measurement honest, and it is unchanged by the proposal network having
seen the inference model many times.

Within that, the variants span the two nuisances the real-data study measured:
skull conductivity, and a *small* residual electrode error. The residual is small
on purpose: an electrode montage that has been registered to an anatomy at all
leaves a few millimetres of scatter, not a centimetre, so a 10 mm montage error
is what a registration step removes rather than what an estimator has to
tolerate.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

__all__ = [
    "DEFAULT_VARIANTS",
    "BankSpec",
    "ForwardVariant",
    "TemplateForward",
    "sample_positions",
    "build_bank",
    "save_bank",
    "load_bank",
    "source_term_invariance",
    "Bank",
]


@dataclass(frozen=True)
class ForwardVariant:
    """One head model in the training distribution.

    Attributes:
        name: Short label, written into the artifact.
        skull_conductivity: Skull conductivity in S/m. The inference model is
            fixed at 0.006 (a 50:1 ratio against 0.3 S/m brain and scalp).
        electrode_rms_mm: RMS tangential displacement applied to every electrode,
            millimetres. Sized from the residual the geometry-only registration
            leaves, not from an uncorrected montage error.
        electrode_seed: Seed for that displacement, so the perturbed array is a
            property of the variant rather than of a training sample.
    """

    name: str
    skull_conductivity: float = 0.006
    electrode_rms_mm: float = 0.0
    electrode_seed: int = 0

    @property
    def is_nominal(self) -> bool:
        """Whether this is the inference model itself."""
        return self.electrode_rms_mm == 0.0 and self.skull_conductivity == 0.006

    @property
    def skull_ratio(self) -> float:
        """Brain-to-skull conductivity ratio."""
        return 0.3 / self.skull_conductivity

    def to_dict(self) -> dict[str, Any]:
        """JSON-serializable record."""
        return {
            "name": self.name,
            "skull_conductivity": self.skull_conductivity,
            "skull_ratio": self.skull_ratio,
            "electrode_rms_mm": self.electrode_rms_mm,
            "electrode_seed": self.electrode_seed,
            "is_nominal": self.is_nominal,
        }


#: The training head-model distribution.
#:
#: ``nominal`` is the inference model, and it is deliberately in the set: an
#: estimator that only works when the head model is wrong would be a strange
#: thing to have built. The other five span the two nuisances the real-data
#: studies measured, at the magnitudes those studies found — a skull ratio from
#: 25:1 to 91:1, and an electrode residual of 1–3 mm.
DEFAULT_VARIANTS: tuple[ForwardVariant, ...] = (
    ForwardVariant("nominal"),
    ForwardVariant("skull-thin", skull_conductivity=0.0033),
    ForwardVariant("skull-thick", skull_conductivity=0.0120),
    ForwardVariant("montage-1mm", electrode_rms_mm=1.0, electrode_seed=101),
    ForwardVariant("montage-3mm", electrode_rms_mm=3.0, electrode_seed=202),
    ForwardVariant(
        "skull-montage", skull_conductivity=0.0045, electrode_rms_mm=2.0,
        electrode_seed=303,
    ),
)


@dataclass(frozen=True)
class BankSpec:
    """How the bank of source positions is drawn.

    Attributes:
        n_positions: How many continuous positions to assemble a source term for.
        cortical_fraction: Share drawn from the cortical surface. The rest are
            drawn uniformly inside the brain compartment, so a proposal that has
            to explain a deep source has seen one.
        normal_jitter_mm: Standard deviation of the displacement along the local
            cortical normal, millimetres. This is what takes the training
            positions off *every* source space in the project — including the
            ico5 space the benchmark's ground truths are drawn between — so a
            network cannot learn to snap to a candidate.
        margin_mm: Clearance kept from the inner-skull surface. The BEM degrades
            for a dipole sitting on an interface.
        seed: Draw seed.
    """

    n_positions: int = 240_000
    cortical_fraction: float = 0.8
    normal_jitter_mm: float = 2.0
    margin_mm: float = 3.0
    seed: int = 20260824

    def fingerprint(self) -> str:
        """Digest of everything that changes the drawn positions."""
        payload = json.dumps(
            {
                "n_positions": self.n_positions,
                "cortical_fraction": self.cortical_fraction,
                "normal_jitter_mm": self.normal_jitter_mm,
                "margin_mm": self.margin_mm,
                "seed": self.seed,
            },
            sort_keys=True,
        )
        return hashlib.sha256(payload.encode()).hexdigest()[:16]

    def to_dict(self) -> dict[str, Any]:
        """JSON-serializable record."""
        return {
            "n_positions": self.n_positions,
            "cortical_fraction": self.cortical_fraction,
            "normal_jitter_mm": self.normal_jitter_mm,
            "margin_mm": self.margin_mm,
            "seed": self.seed,
            "fingerprint": self.fingerprint(),
        }


def _surface_info(vertices: np.ndarray, triangles: np.ndarray) -> Any:
    """MNE's completed surface record for the inner skull.

    MNE is imported here, and only here, because the bank is built **offline**.
    Nothing on the inference path — the components, the optimizer, the proposal
    network — imports it, exactly as :mod:`neurolayout.mismatch` keeps the
    generating forward model out of the estimator.
    """
    from mne.surface import complete_surface_info

    return complete_surface_info(
        {
            "rr": np.asarray(vertices, dtype=np.float64),
            "tris": np.asarray(triangles, dtype=np.int64),
            "np": len(vertices),
            "ntri": len(triangles),
        },
        copy=True,
        verbose="ERROR",
    )


def _inside_with_margin(points_m: np.ndarray, surface: Any, margin_m: float) -> np.ndarray:
    """Mask of points inside a closed surface by at least ``margin_m``.

    Clearance is measured to the *surface*, not to its nearest vertex. On the
    decimated ico3 inner skull the vertex spacing is about 8 mm, so a
    vertex-distance test would reject a band of legitimate deep positions and
    accept some sitting on a facet.
    """
    from mne.surface import _points_outside_surface, _project_onto_surface

    points = np.atleast_2d(np.asarray(points_m, dtype=np.float64))
    keep = np.empty(len(points), dtype=bool)
    for start in range(0, len(points), 20_000):
        block = points[start : start + 20_000]
        inside = ~_points_outside_surface(block, surface, n_jobs=1, verbose="ERROR")
        nearest = np.asarray(
            _project_onto_surface(block, surface, project_rrs=True)[2], dtype=np.float64
        )
        keep[start : start + 20_000] = inside & (
            np.linalg.norm(block - nearest, axis=1) >= margin_m
        )
    return keep


def sample_positions(
    geometry: Any, spec: BankSpec
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Draw the bank's source positions.

    Cortical draws are a random point in a random triangle of the source-space
    mesh — approximated here by a random convex combination of a vertex and two of
    its nearest neighbours, since the artifact stores the decimated source space
    as points rather than as a mesh — displaced along the interpolated normal.
    Volumetric draws are rejection-sampled inside the inner skull.

    Args:
        geometry: A :class:`~neurolayout_shared.openmeeg_model.HeadGeometry`.
        spec: The draw specification.

    Returns:
        ``(positions_m [N, 3], normals [N, 3], is_cortical [N])``. The normals are
        unit cortical normals for cortical draws and a random unit vector for
        volumetric ones; they are the *orientation prior*, not a constraint —
        :mod:`neurolayout.hybrid.synth` perturbs them.
    """
    rng = np.random.default_rng(spec.seed)
    source_space = np.asarray(geometry.source_space, dtype=np.float64)
    source_normals = np.asarray(geometry.source_normals, dtype=np.float64)
    surface = _surface_info(geometry.vertices[0], geometry.triangles[0])
    margin_m = spec.margin_mm * 1e-3

    n_cortical = int(round(spec.n_positions * spec.cortical_fraction))
    n_volume = spec.n_positions - n_cortical

    neighbours = _nearest_neighbours(source_space, k=3, rng=rng)
    anchors = rng.integers(0, len(source_space), n_cortical)
    picks = neighbours[anchors]  # [n, 3] the vertex and two neighbours
    weights = rng.dirichlet(np.ones(3), size=n_cortical)
    cortical = np.einsum("nk,nkj->nj", weights, source_space[picks])
    normals = np.einsum("nk,nkj->nj", weights, source_normals[picks])
    normals /= np.maximum(np.linalg.norm(normals, axis=1, keepdims=True), 1e-30)
    cortical = cortical + (
        normals * rng.normal(0.0, spec.normal_jitter_mm * 1e-3, (n_cortical, 1))
    )

    volume, volume_normals = _volume_draws(rng, surface, n_volume, margin_m)

    positions = np.concatenate([cortical, volume], axis=0)
    all_normals = np.concatenate([normals, volume_normals], axis=0)
    is_cortical = np.concatenate(
        [np.ones(n_cortical, dtype=bool), np.zeros(n_volume, dtype=bool)]
    )
    # A cortical draw plus jitter can land outside; drop it rather than clamp it,
    # so the accepted set is exactly "positions the BEM is valid at".
    inside = _inside_with_margin(positions, surface, margin_m)
    order = rng.permutation(int(inside.sum()))
    return positions[inside][order], all_normals[inside][order], is_cortical[inside][order]


def _volume_draws(
    rng: np.random.Generator, surface: Any, count: int, margin_m: float
) -> tuple[np.ndarray, np.ndarray]:
    """Rejection-sample ``count`` points uniformly inside the inner skull."""
    vertices = np.asarray(surface["rr"], dtype=np.float64)
    low, high = vertices.min(axis=0), vertices.max(axis=0)
    kept: list[np.ndarray] = []
    total = 0
    while total < count:
        batch = rng.uniform(low, high, size=(max(count, 1024), 3))
        batch = batch[_inside_with_margin(batch, surface, margin_m)]
        kept.append(batch)
        total += len(batch)
    points = np.concatenate(kept, axis=0)[:count]
    directions = rng.standard_normal((len(points), 3))
    directions /= np.maximum(np.linalg.norm(directions, axis=1, keepdims=True), 1e-30)
    return points, directions


def _nearest_neighbours(points: np.ndarray, k: int, rng: np.random.Generator) -> np.ndarray:
    """``[N, k]`` indices of each point and its ``k-1`` nearest others."""
    out = np.empty((len(points), k), dtype=np.int64)
    for start in range(0, len(points), 512):
        chunk = points[start : start + 512]
        distance = np.linalg.norm(chunk[:, None, :] - points[None, :, :], axis=2)
        out[start : start + 512] = np.argsort(distance, axis=1)[:, :k]
    return out


def scalp_potential_block(om_geometry: Any, scalp: dict[str, np.ndarray], om: Any) -> slice:
    """Locate the block of BEM unknowns that holds the scalp potential.

    Derived, not hard-coded. ``Head2EEGMat`` interpolates the outermost
    interface's potential, so building it at the barycentre of every scalp
    triangle touches every scalp-potential unknown and nothing else; the union
    of its non-zero columns is the block.

    Args:
        om_geometry: The OpenMEEG geometry.
        scalp: ``{"rr", "tris"}`` of the outer-skin surface, head frame.
        om: The imported ``openmeeg`` module.

    Returns:
        The contiguous column range.

    Raises:
        RuntimeError: If the touched columns are not one contiguous block of
            exactly one unknown per scalp vertex, which would mean the solver's
            unknown ordering is not what this factorization assumes.
    """
    vertices = np.asarray(scalp["rr"], dtype=np.float64)
    triangles = np.asarray(scalp["tris"], dtype=np.int64)
    centres = vertices[triangles].mean(axis=1)
    matrix = om.Matrix(np.asfortranarray(centres))
    sensors = om.Sensors(matrix, om_geometry)
    dense = np.array(om.Matrix(om.Head2EEGMat(om_geometry, sensors)).array())
    columns = np.nonzero((dense != 0.0).any(axis=0))[0]
    start, stop = int(columns.min()), int(columns.max()) + 1
    if stop - start != len(vertices) or len(columns) != len(vertices):
        raise RuntimeError(
            f"the scalp-potential unknowns are not a contiguous block: touched "
            f"{len(columns)} columns spanning {start}..{stop} for {len(vertices)} "
            "scalp vertices"
        )
    return slice(start, stop)


class TemplateForward:
    r"""The template head's BEM, re-solvable over the training head models.

    Holds the pieces of :math:`G = R\,S(e)\,A(\sigma)^{-1} D(p)` separately, so a
    set of source positions can be pushed through every variant for the price of
    one source-term assembly.

    It is asked for gains at whatever positions the caller drew, never at a fixed
    candidate grid.

    Args:
        geometry: A :class:`~neurolayout_shared.openmeeg_model.HeadGeometry`.
    """

    def __init__(self, geometry: Any) -> None:
        """Build the OpenMEEG geometry cache and locate the scalp-potential block."""
        import openmeeg as om

        self.geometry = geometry
        self._om = om
        self._geom_cache: dict[float, Any] = {}
        self._rows_cache: dict[float, np.ndarray] = {}
        self._scalp = {
            "rr": np.asarray(geometry.vertices[2], dtype=np.float64),
            "tris": np.asarray(geometry.triangles[2], dtype=np.int64),
        }
        self._scalp_block = scalp_potential_block(
            self._om_geometry(0.006), self._scalp, om
        )
        self._reference = geometry.reference_operator()

    def _om_geometry(self, skull_sigma: float) -> Any:
        """The OpenMEEG nested geometry at one skull conductivity, memoized."""
        from neurolayout_shared.openmeeg_model import openmeeg_triangles

        key = float(skull_sigma)
        cached = self._geom_cache.get(key)
        if cached is not None:
            return cached
        meshes = [
            (np.ascontiguousarray(verts, dtype=np.float64), openmeeg_triangles(verts, tris))
            for verts, tris in zip(
                self.geometry.vertices, self.geometry.triangles, strict=True
            )
        ]
        conductivities = list(np.asarray(self.geometry.conductivities, dtype=np.float64))
        conductivities[1] = key
        built = self._om.make_nested_geometry(meshes, conductivities)
        if not built.is_nested():
            raise ValueError("OpenMEEG rejected the template surfaces as non-nested")
        self._geom_cache[key] = built
        return built

    def scalp_rows(self, skull_sigma: float) -> np.ndarray:
        r"""``[V3, n]`` — the scalp-potential rows of :math:`A(\sigma)^{-1}`.

        ``A`` is symmetric, so the wanted rows are the columns at the same
        indices, which is one solve against the corresponding unit vectors. On the
        ico3 template that is 642 right-hand sides against a 4486-unknown system —
        seconds, and everything ``S(e) A^{-1}`` can reach for *any* montage.
        """
        key = float(skull_sigma)
        cached = self._rows_cache.get(key)
        if cached is not None:
            return cached
        system = _dense(self._om, self._om.HeadMat(self._om_geometry(key)))
        width = self._scalp_block.stop - self._scalp_block.start
        selector = np.zeros((system.shape[0], width), dtype=np.float64)
        selector[
            np.arange(self._scalp_block.start, self._scalp_block.stop), np.arange(width)
        ] = 1.0
        rows = np.ascontiguousarray(np.linalg.solve(system, selector).T)
        self._rows_cache[key] = rows
        return rows

    def sensor_matrix(self, electrodes_m: np.ndarray, skull_sigma: float) -> np.ndarray:
        """``[C, V3]`` — ``Head2EEGMat`` restricted to the scalp-potential block."""
        geometry = self._om_geometry(float(skull_sigma))
        matrix = self._om.Matrix(
            np.asfortranarray(np.asarray(electrodes_m, dtype=np.float64))
        )
        sensors = self._om.Sensors(matrix, geometry)
        dense = _dense(self._om, self._om.Head2EEGMat(geometry, sensors))
        outside = dense.copy()
        outside[:, self._scalp_block] = 0.0
        if np.abs(outside).max() > 0.0:
            raise RuntimeError(
                "Head2EEGMat touched unknowns outside the scalp-potential block; "
                "the factorization the bank rests on is invalid for this geometry"
            )
        return np.ascontiguousarray(dense[:, self._scalp_block])

    def sensor_operator(self, variant: ForwardVariant) -> np.ndarray:
        """``[C, n]`` — ``R S(e) A(σ)^{-1}`` for one variant, average-referenced."""
        electrodes = self.electrodes(variant)
        sensor = self.sensor_matrix(electrodes, variant.skull_conductivity)
        return self._reference @ (sensor @ self.scalp_rows(variant.skull_conductivity))

    def electrodes(self, variant: ForwardVariant) -> np.ndarray:
        """``[C, 3]`` electrode positions for one variant."""
        canonical = np.asarray(self.geometry.sensor_xyz, dtype=np.float64)
        if variant.electrode_rms_mm <= 0.0:
            return canonical
        from neurolayout.mismatch import _displaced_electrodes

        return _displaced_electrodes(
            canonical, self._scalp["rr"], variant.electrode_rms_mm, variant.electrode_seed
        )

    def source_term(
        self, positions_m: np.ndarray, skull_sigma: float = 0.006
    ) -> np.ndarray:
        """``[n, 3P]`` — one real ``DipSourceMat`` assembly for three axes per position.

        ``skull_sigma`` exists so the invariance the bank rests on can be
        *measured*; the bank itself always assembles at the default, because the
        source term does not depend on it.
        """
        positions = np.atleast_2d(np.asarray(positions_m, dtype=np.float64))
        dipoles = np.empty((3 * len(positions), 6), dtype=np.float64)
        dipoles[:, :3] = np.repeat(positions, 3, axis=0)
        dipoles[:, 3:] = np.tile(np.eye(3), (len(positions), 1))
        matrix = self._om.Matrix(np.asfortranarray(dipoles))
        return _dense(
            self._om,
            self._om.DipSourceMat(self._om_geometry(float(skull_sigma)), matrix, "Brain"),
        )

    def release(self) -> None:
        """Drop the cached solves (tens of megabytes each)."""
        self._rows_cache = {}


def _dense(om: Any, matrix: Any) -> np.ndarray:
    """Copy an OpenMEEG matrix into an owned float64 array.

    ``.array()`` is a view into a temporary; binding the wrapper to a local first
    is what keeps the buffer alive long enough for the copy.
    """
    full = matrix if isinstance(matrix, om.Matrix) else om.Matrix(matrix)
    return np.array(full.array(), dtype=np.float64, copy=True)


def source_term_invariance(forward: TemplateForward) -> float:
    """Largest relative disagreement between source terms at two skull conductivities.

    The bank assembles ``D`` once and reuses it for every variant. That is only
    valid because ``D`` is built from the primary field in the source's *own*
    compartment, whose conductivity (brain, 0.3 S/m) no variant changes. The claim
    is cheap to check and expensive to get wrong, so it is measured rather than
    asserted.

    Returns:
        ``max|D(0.006) - D(0.012)| / max|D(0.006)|``. Expected at round-off.
    """
    probe = np.asarray(forward.geometry.source_space[:8], dtype=np.float64) * 0.9
    first = forward.source_term(probe, 0.006)
    second = forward.source_term(probe, 0.012)
    return float(np.abs(first - second).max() / max(np.abs(first).max(), 1e-300))


@dataclass(frozen=True)
class Bank:
    """A built gain bank, memory-mapped.

    Attributes:
        positions_m: ``[N, 3]`` source positions, metres, MNE head frame.
        normals: ``[N, 3]`` unit orientation priors.
        is_cortical: ``[N]`` whether the position came from the cortical draw.
        depth_mm: ``[N]`` distance to the nearest inner-skull vertex.
        gains: ``[V, N, C, 3]`` volts per A·m, average-referenced, float32.
        variants: The ``V`` head models, in the order of ``gains``.
        channel_names: The frozen ``C``-channel order.
        sensor_xyz: ``[C, 3]`` canonical electrode positions, metres. The
            *nominal* montage — a variant's own displaced positions are part of
            the head model it represents, and the estimator never sees them.
        metadata: Provenance, including the head-model fingerprint.
    """

    positions_m: np.ndarray
    normals: np.ndarray
    is_cortical: np.ndarray
    depth_mm: np.ndarray
    gains: np.ndarray
    variants: tuple[ForwardVariant, ...]
    channel_names: tuple[str, ...]
    sensor_xyz: np.ndarray
    metadata: dict[str, Any]

    @property
    def n_positions(self) -> int:
        """``N``."""
        return int(self.positions_m.shape[0])

    @property
    def n_channels(self) -> int:
        """``C``."""
        return int(self.gains.shape[2])

    def variant_index(self, name: str) -> int:
        """Index of a variant by name."""
        for index, variant in enumerate(self.variants):
            if variant.name == name:
                return index
        raise KeyError(f"no variant {name!r} in this bank: {[v.name for v in self.variants]}")

    def split(self, holdout_fraction: float, seed: int = 7) -> tuple[np.ndarray, np.ndarray]:
        """Disjoint ``(train, validation)`` position indices.

        Split on *position*, not on sample, so a validation source is one the
        network has never had a gain for — not merely one it has not seen in this
        combination of moment, waveform and noise.
        """
        rng = np.random.default_rng(seed)
        order = rng.permutation(self.n_positions)
        cut = int(round(self.n_positions * (1.0 - holdout_fraction)))
        return np.sort(order[:cut]), np.sort(order[cut:])


def build_bank(
    geometry: Any,
    spec: BankSpec,
    variants: tuple[ForwardVariant, ...] = DEFAULT_VARIANTS,
    *,
    chunk: int = 2048,
    progress: Any = None,
) -> dict[str, Any]:
    """Assemble the gain bank.

    One ``DipSourceMat`` call per chunk of positions; every variant is then a
    matrix product against it. The cost is therefore set by ``spec.n_positions``
    and is almost independent of how many variants there are.

    Args:
        geometry: The template :class:`HeadGeometry`.
        spec: The position draw.
        variants: The head models to evaluate.
        chunk: Positions per OpenMEEG assembly.
        progress: Optional callable ``(done, total)`` for a progress line.

    Returns:
        A dict of arrays and metadata, ready for :func:`save_bank`.
    """
    forward = TemplateForward(geometry)
    invariance = source_term_invariance(forward)
    if invariance > 1e-12:
        raise RuntimeError(
            f"the source term moved by {invariance:.3g} between skull "
            "conductivities; the bank's one-assembly-many-head-models "
            "factorization is invalid for this geometry"
        )

    positions, normals, is_cortical = sample_positions(geometry, spec)
    operators = np.stack([forward.sensor_operator(v) for v in variants])  # [V, C, n]
    n_variants, n_channels = operators.shape[0], operators.shape[1]
    gains = np.empty((n_variants, len(positions), n_channels, 3), dtype=np.float32)

    for start in range(0, len(positions), chunk):
        block = positions[start : start + chunk]
        term = forward.source_term(block)  # [n, 3P]
        for index in range(n_variants):
            flat = operators[index] @ term  # [C, 3P]
            gains[index, start : start + len(block)] = np.ascontiguousarray(
                flat.reshape(n_channels, len(block), 3).transpose(1, 0, 2)
            ).astype(np.float32)
        if progress is not None:
            progress(min(start + chunk, len(positions)), len(positions))

    inner = np.asarray(geometry.vertices[0], dtype=np.float64)
    depth = np.empty(len(positions), dtype=np.float32)
    for start in range(0, len(positions), 4096):
        block = positions[start : start + 4096]
        depth[start : start + 4096] = (
            np.linalg.norm(block[:, None, :] - inner[None, :, :], axis=2).min(axis=1) * 1e3
        )

    forward.release()
    return {
        "positions_m": positions,
        "normals": normals,
        "is_cortical": is_cortical,
        "depth_mm": depth,
        "gains": gains,
        "variants": variants,
        "channel_names": tuple(geometry.channel_names),
        "sensor_xyz": np.asarray(geometry.sensor_xyz, dtype=np.float64),
        "metadata": {
            "spec": spec.to_dict(),
            "head_model_fingerprint": geometry.fingerprint(),
            "source_term_invariance": invariance,
            "solver": "openmeeg-symmetric-bem ico3 fsaverage",
            "units": "V per A m, average-referenced",
            "coord_frame": "mne-head",
        },
    }


def save_bank(path: str | Path, built: dict[str, Any]) -> Path:
    """Write a built bank to one ``.npz``."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez(
        path,
        positions_m=built["positions_m"],
        normals=built["normals"],
        is_cortical=built["is_cortical"],
        depth_mm=built["depth_mm"],
        gains=built["gains"],
        sensor_xyz=built["sensor_xyz"],
        channel_names=np.array(built["channel_names"], dtype="U16"),
        variants=np.array(
            json.dumps([v.to_dict() for v in built["variants"]], sort_keys=True)
        ),
        metadata=np.array(json.dumps(built["metadata"], sort_keys=True)),
    )
    return path


def load_bank(path: str | Path, *, mmap: bool = True) -> Bank:
    """Read a bank written by :func:`save_bank`.

    Memory-mapped by default: the gain array is the large part and the data loader
    touches a few thousand rows of it at a time.
    """
    data = np.load(path, allow_pickle=False, mmap_mode="r" if mmap else None)
    variants = tuple(
        ForwardVariant(
            name=entry["name"],
            skull_conductivity=entry["skull_conductivity"],
            electrode_rms_mm=entry["electrode_rms_mm"],
            electrode_seed=entry["electrode_seed"],
        )
        for entry in json.loads(str(data["variants"]))
    )
    return Bank(
        positions_m=np.asarray(data["positions_m"]),
        normals=np.asarray(data["normals"]),
        is_cortical=np.asarray(data["is_cortical"]),
        depth_mm=np.asarray(data["depth_mm"]),
        gains=data["gains"],
        variants=variants,
        channel_names=tuple(str(name) for name in data["channel_names"]),
        sensor_xyz=np.asarray(data["sensor_xyz"]),
        metadata=json.loads(str(data["metadata"])),
    )
