# Copyright 2026 NeuroLocate contributors
# SPDX-License-Identifier: Apache-2.0
r"""Supervised training of the proposal network, and the validation that judges it.

This is Gate 1: does a learned global proposal solve the *global* half of the
problem — does it land in the right basin — on held-out hard cases? If it does
not, nothing downstream is worth running, and the honest move is to stop.

What "held out" means here
--------------------------
Three things at once, and they are separable on purpose:

1. **Held-out sources.** The validation split is a disjoint set of bank
   positions, so a validation source is one the network has never had a gain for.
2. **Held-out forward model.** One head-model variant is kept out of training
   entirely, so the validation set includes physics the network has not seen.
3. **Held-out generator.** The *benchmark* is generated by MNE-Python's
   linear-collocation BEM on ico4 — a solver, a formulation and a discretization
   that appear nowhere in the bank. That is the real test, and it lives in
   :mod:`neurolayout.hybrid.benchmark`.

The reference the proposal has to beat
--------------------------------------
"Better than nothing" has to be a number. The comparison recorded at every
validation is against the *initialization the gradient-only estimator actually
uses* — a random draw inside the brain, far from every truth, which
``neurolayout.benchmark.random_initialization`` defines and the frozen benchmark
has always used. That is the thing the proposal replaces, so it is the thing the
proposal is measured against.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import torch

from neurolayout.hybrid.bank import Bank
from neurolayout.hybrid.losses import LossWeights, proposal_loss
from neurolayout.hybrid.model import ProposalNet, decode
from neurolayout.hybrid.synth import Synthesizer, SynthSpec

__all__ = [
    "TrainConfig",
    "batch_to_torch",
    "evaluate",
    "train",
]


@dataclass(frozen=True)
class TrainConfig:
    """Everything that defines a supervised training run.

    Attributes:
        steps: Optimizer steps.
        batch_size: Samples per step.
        learning_rate: Peak AdamW step size.
        weight_decay: AdamW decay.
        warmup: Linear warmup steps.
        grad_clip: Global gradient-norm clip.
        eval_every: Validation interval, in steps.
        eval_batches: Validation batches per evaluation.
        eval_batch_size: Samples per validation batch.
        holdout_fraction: Share of bank positions reserved for validation.
        holdout_variant: A head model kept out of training entirely, or ``None``.
        seed: Deterministic seed for the draw and the initialization.
        device: Torch device.
        workers: DataLoader worker processes for batch construction. 0 builds
            batches in the training process, which is right on CPU and wrong
            on a GPU, where the network step is seventeen times faster and the
            draw becomes the whole run.
        loss: Term weights.
        spec: The training distribution.
    """

    steps: int = 30_000
    batch_size: int = 96
    learning_rate: float = 3e-4
    weight_decay: float = 0.01
    warmup: int = 500
    grad_clip: float = 1.0
    eval_every: int = 1000
    eval_batches: int = 8
    eval_batch_size: int = 64
    holdout_fraction: float = 0.08
    holdout_variant: str | None = "skull-montage"
    seed: int = 20260824
    device: str = "cpu"
    workers: int = 0
    loss: LossWeights = field(default_factory=LossWeights)
    spec: SynthSpec = field(default_factory=SynthSpec)

    def to_dict(self) -> dict[str, Any]:
        """JSON-serializable record. This is what goes in the checkpoint."""
        return {
            "steps": self.steps,
            "batch_size": self.batch_size,
            "learning_rate": self.learning_rate,
            "weight_decay": self.weight_decay,
            "warmup": self.warmup,
            "grad_clip": self.grad_clip,
            "eval_every": self.eval_every,
            "eval_batches": self.eval_batches,
            "eval_batch_size": self.eval_batch_size,
            "holdout_fraction": self.holdout_fraction,
            "holdout_variant": self.holdout_variant,
            "seed": self.seed,
            "device": self.device,
            "workers": self.workers,
            "loss": self.loss.to_dict(),
            "spec": self.spec.to_dict(),
        }


def batch_to_torch(batch: dict[str, Any], device: str) -> dict[str, torch.Tensor]:
    """The synthesizer's arrays as float64 tensors on ``device``.

    float64 throughout: the network is small, the epochs are 64x32, and the
    composed gradient downstream crosses a Tesseract boundary whose schema is
    float64. Matching dtypes end to end removes a class of silent precision
    surprises for a cost that does not show up in the profile.
    """
    return {
        "eeg": torch.as_tensor(batch["eeg"], dtype=torch.float64, device=device),
        "channel_mask": torch.as_tensor(
            batch["channel_mask"], dtype=torch.float64, device=device
        ),
        "positions_m": torch.as_tensor(
            batch["positions_m"], dtype=torch.float64, device=device
        ),
        "moments_nam": torch.as_tensor(
            batch["moments_nam"], dtype=torch.float64, device=device
        ),
        "source_mask": torch.as_tensor(
            batch["source_mask"], dtype=torch.float64, device=device
        ),
        "n_sources": torch.as_tensor(
            batch["n_sources"], dtype=torch.long, device=device
        ),
    }


def _summary(errors: list[np.ndarray]) -> dict[str, float]:
    """Median, IQR and gross-failure rate over a list of per-source error arrays."""
    if not errors:
        return {"median_mm": float("nan"), "n": 0}
    flat = np.concatenate(errors)
    worst = np.array([e.max() for e in errors])
    return {
        "median_mm": float(np.median(flat)),
        "q1_mm": float(np.percentile(flat, 25)),
        "q3_mm": float(np.percentile(flat, 75)),
        "mean_mm": float(flat.mean()),
        "worst_mm": float(flat.max()),
        "median_worst_mm": float(np.median(worst)),
        "gross_failure_rate": float((worst > 20.0).mean()),
        "n": int(len(errors)),
    }


@torch.no_grad()
def evaluate(
    model: ProposalNet,
    synthesizer: Synthesizer,
    config: TrainConfig,
    *,
    seed: int,
    containment: Any,
    nms_radius_m: float = 0.010,
) -> dict[str, Any]:
    """Decode on held-out data and score by the assignment metric.

    Reports overall and split by the axis that matters: the correlation regime. A
    method that is good on distinct dynamics and useless on shared ones is what
    the existing benchmark already has.

    Args:
        model: The network.
        synthesizer: A validation synthesizer — held-out positions, and a
            head-model variant training never saw.
        config: The run configuration.
        seed: Deterministic seed, so two evaluations of the same checkpoint agree.
        containment: The benchmark's own containment ellipsoid, used to draw the
            uninformed-initialization reference from the same distribution the
            gradient-only estimator starts from.
        nms_radius_m: Suppression radius for the decode.

    Returns:
        A nested summary: overall, by correlation regime, by ``K``, the
        uninformed-initialization reference, and the count head's accuracy.
    """
    from neurolayout.benchmark import random_initialization
    from neurolayout.matching import match_sources

    model.eval()
    rng = np.random.default_rng(seed)
    per_mode: dict[str, list[np.ndarray]] = {}
    per_k: dict[int, list[np.ndarray]] = {}
    everything: list[np.ndarray] = []
    baseline: list[np.ndarray] = []
    count_right, count_total = 0, 0

    for _ in range(config.eval_batches):
        batch = synthesizer.batch(rng, config.eval_batch_size)
        tensors = batch_to_torch(batch, config.device)
        outputs = model(tensors["eeg"], tensors["channel_mask"])
        for index, sample in enumerate(batch["samples"]):
            single = {
                key: value[index : index + 1] for key, value in outputs.items()
            }
            picked = decode(
                single,
                sample.n_sources,
                nms_radius_m=nms_radius_m,
                max_sources=model.config.max_sources,
            )
            errors = match_sources(
                picked["positions_m"][0].cpu().numpy(), sample.positions_m
            ).errors_mm
            everything.append(errors)
            per_mode.setdefault(sample.correlation_mode, []).append(errors)
            per_k.setdefault(sample.n_sources, []).append(errors)
            count_total += 1
            count_right += int(picked["n_predicted"].item() == sample.n_sources)
            start = random_initialization(containment, sample.positions_m, rng)
            baseline.append(match_sources(start, sample.positions_m).errors_mm)

    model.train()
    return {
        "overall": _summary(everything),
        "by_correlation": {
            mode: _summary(values) for mode, values in sorted(per_mode.items())
        },
        "by_k": {str(k): _summary(values) for k, values in sorted(per_k.items())},
        "uninformed_initialization": _summary(baseline),
        "count_accuracy": count_right / max(count_total, 1),
        "nms_radius_m": nms_radius_m,
    }


def _schedule(step: int, config: TrainConfig) -> float:
    """Linear warmup, then cosine decay to a tenth of the peak."""
    if step < config.warmup:
        return (step + 1) / max(config.warmup, 1)
    progress = (step - config.warmup) / max(config.steps - config.warmup, 1)
    return 0.1 + 0.9 * 0.5 * (1.0 + np.cos(np.pi * min(progress, 1.0)))


def train(
    model: ProposalNet,
    bank: Bank,
    config: TrainConfig,
    *,
    containment: Any,
    bank_path: str | Path | None = None,
    on_log: Any = None,
    checkpoint_path: str | Path | None = None,
    metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Run supervised training and return the history.

    Args:
        model: The network, in train mode.
        bank: The gain bank.
        config: The run configuration.
        containment: The benchmark's containment ellipsoid, for the reference.
        bank_path: Where the bank lives, required when ``config.workers > 0``
            so each worker can memory-map its own view of it.
        on_log: Optional ``(record) -> None`` called at every log point.
        checkpoint_path: Where to write the checkpoint, rewritten at every
            evaluation so a kill costs one interval rather than the run.
        metadata: Extra provenance written into the checkpoint.

    Returns:
        A dict with the loss history, the evaluation history, and timings.
    """
    from neurolayout.hybrid.model import save_checkpoint

    train_indices, validation_indices = bank.split(config.holdout_fraction, config.seed)
    train_variants = tuple(
        variant.name
        for variant in bank.variants
        if variant.name != config.holdout_variant
    )
    validation = Synthesizer(bank, config.spec, indices=validation_indices)
    if config.workers > 0:
        if bank_path is None:
            raise ValueError("workers > 0 needs bank_path so each worker can map the bank")
        batches = iter(
            _loader(
                SampleStream(
                    bank_path,
                    config.spec,
                    train_indices,
                    train_variants,
                    config.batch_size,
                    config.seed + 1,
                ),
                config.workers,
            )
        )
    else:
        training = Synthesizer(
            bank, config.spec, indices=train_indices, variants=train_variants
        )
        stream_rng = np.random.default_rng(config.seed + 1)
        batches = iter(
            lambda: training.batch(
                stream_rng, config.batch_size, with_samples=False
            ),
            None,
        )

    model.to(config.device).double().train()
    optimizer = torch.optim.AdamW(
        model.parameters(), lr=config.learning_rate, weight_decay=config.weight_decay
    )
    centres = model.voxel_centres.to(config.device).double()

    history: list[dict[str, Any]] = []
    evaluations: list[dict[str, Any]] = []
    started = time.perf_counter()
    running: dict[str, float] = {}

    for step in range(config.steps):
        for group in optimizer.param_groups:
            group["lr"] = config.learning_rate * _schedule(step, config)
        batch = batch_to_torch(next(batches), config.device)
        outputs = model(batch["eeg"], batch["channel_mask"])
        loss, parts = proposal_loss(
            outputs, batch, centres, config.loss, pitch_m=model.config.grid_pitch_m
        )
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), config.grad_clip)
        optimizer.step()

        for key, value in parts.items():
            running[key] = running.get(key, 0.0) + value
        if (step + 1) % 100 == 0:
            record = {
                "step": step + 1,
                "seconds": time.perf_counter() - started,
                "lr": optimizer.param_groups[0]["lr"],
                "grad_norm": float(grad_norm),
                **{key: value / 100.0 for key, value in running.items()},
            }
            running = {}
            history.append(record)
            if on_log is not None:
                on_log(record)

        if (step + 1) % config.eval_every == 0 or step + 1 == config.steps:
            summary = evaluate(
                model,
                validation,
                config,
                seed=config.seed + 7,
                containment=containment,
            )
            summary["step"] = step + 1
            summary["seconds"] = time.perf_counter() - started
            evaluations.append(summary)
            if on_log is not None:
                on_log({"evaluation": summary})
            if checkpoint_path is not None:
                save_checkpoint(
                    checkpoint_path,
                    model,
                    {
                        **(metadata or {}),
                        "config": config.to_dict(),
                        "bank": bank.metadata,
                        "step": step + 1,
                        "evaluation": summary,
                        "n_parameters": model.n_parameters(),
                    },
                )

    return {
        "history": history,
        "evaluations": evaluations,
        "seconds": time.perf_counter() - started,
        "n_parameters": model.n_parameters(),
        "n_voxels": model.n_voxels,
        "train_positions": int(len(train_indices)),
        "validation_positions": int(len(validation_indices)),
        "train_variants": list(train_variants),
    }


class SampleStream(torch.utils.data.IterableDataset):
    """An endless stream of training batches, one Synthesizer per worker.

    Batch construction is Python: a tree query per source to hit the requested
    separation band, a Gram-Schmidt for the correlated time courses, a Cholesky
    for the noise. On CPU that cost is a quarter of a training step and does not
    matter. On a GPU the network step drops seventeenfold and the same cost
    becomes the whole run, so it is moved off the training process.

    Each worker builds its own :class:`~neurolayout.hybrid.synth.Synthesizer` over
    a **memory-mapped** bank, so the 1.1 GB of gains is shared through the page
    cache rather than copied per worker, and seeds from ``(seed, worker id)`` so
    no two workers draw the same samples.

    Args:
        bank_path: Path to the gain bank.
        spec: The training distribution.
        indices: Bank positions this stream may use.
        variants: Head models this stream may use, by name.
        batch_size: Samples per yielded batch.
        seed: Base seed.
    """

    def __init__(
        self,
        bank_path: str | Path,
        spec: SynthSpec,
        indices: np.ndarray,
        variants: tuple[str, ...],
        batch_size: int,
        seed: int,
    ) -> None:
        """Record what each worker needs to rebuild the synthesizer."""
        super().__init__()
        self.bank_path = str(bank_path)
        self.spec = spec
        self.indices = np.asarray(indices)
        self.variants = tuple(variants)
        self.batch_size = int(batch_size)
        self.seed = int(seed)

    def __iter__(self):
        """Yield batches forever."""
        from neurolayout.hybrid.bank import load_bank

        info = torch.utils.data.get_worker_info()
        worker = 0 if info is None else int(info.id)
        synthesizer = Synthesizer(
            load_bank(self.bank_path, mmap=True),
            self.spec,
            indices=self.indices,
            variants=self.variants,
        )
        rng = np.random.default_rng([self.seed, worker])
        while True:
            yield synthesizer.batch(rng, self.batch_size, with_samples=False)


def _loader(stream: SampleStream, workers: int) -> Any:
    """A DataLoader over whole batches — no collation, no re-batching."""
    return torch.utils.data.DataLoader(
        stream,
        batch_size=None,
        num_workers=workers,
        persistent_workers=workers > 0,
        prefetch_factor=4 if workers > 0 else None,
    )
